import { QuizQuestion, ErrorType } from './types';

const m1Data = [
  { q: "What type of sentence is this? \"I love playing cricket.\"", o: ["Question", "Command", "Statement", "Exclamation"], a: "Statement", e: "This sentence gives information about a preference or state." },
  { q: "What type of sentence is this? \"Please close the door.\"", o: ["Statement", "Exclamation", "Question", "Command"], a: "Command", e: "This is a polite order or request to perform an action." },
  { q: "Identify the sentence type: \"What a beautiful sunset!\"", o: ["Statement", "Question", "Command", "Exclamation"], a: "Exclamation", e: "Expresses strong emotion and ends with an exclamation mark." },
  { q: "What type is this? \"Have you finished your homework?\"", o: ["Statement", "Question", "Command", "Exclamation"], a: "Question", e: "Asks for information and ends with a question mark." },
  { q: "\"Work hard and succeed.\" — What type?", o: ["Statement", "Question", "Command", "Exclamation"], a: "Command", e: "This is an instruction or advice given to the listener." },
  { q: "\"The earth is round.\" — What type?", o: ["Statement", "Question", "Command", "Exclamation"], a: "Statement", e: "Provides factual information (declarative)." },
  { q: "\"Hurrah! We won the match!\" — What type?", o: ["Statement", "Question", "Command", "Exclamation"], a: "Exclamation", e: "Uses an interjection to show joy and strong emotion." },
  { q: "\"Where did you go yesterday?\" — What type?", o: ["Statement", "Question", "Command", "Exclamation"], a: "Question", e: "A Wh-question seeking specific information." },
  { q: "\"Don't make noise.\" — What type?", o: ["Statement", "Question", "Command", "Exclamation"], a: "Command", e: "A negative order or prohibition." },
  { q: "What type? \"Tell me where you were and what you did.\"", o: ["Question", "Statement", "Mixed (Command + Question)", "Exclamation"], a: "Mixed (Command + Question)", e: "Combines an instruction (Tell me) with inquiries." },
  { q: "\"Run quickly and hide behind the tree.\" — What type?", o: ["Statement", "Mixed Command", "Question", "Exclamation"], a: "Mixed Command", e: "Contains two commands joined together." },
  { q: "\"Alas! What a tragedy!\" — What type?", o: ["Statement", "Question", "Command", "Exclamation"], a: "Exclamation", e: "Expresses deep sorrow and strong emotion." },
  { q: "Which is a statement?", o: ["\"Close the window!\"", "\"Did you see that?\"", "\"She works at a hospital.\"", "\"How wonderful!\""], a: "\"She works at a hospital.\"", e: "Only this option provides info without asking or ordering." },
  { q: "Which is a question?", o: ["\"I am tired.\"", "\"Are you coming?\"", "\"Please help me.\"", "\"What a surprise!\""], a: "\"Are you coming?\"", e: "This seeks a response from the listener." },
  { q: "Which is a command?", o: ["\"He is sleeping.\"", "\"Is she here?\"", "\"Sit down.\"", "\"Oh no!\""], a: "\"Sit down.\"", e: "Directly instructs the subject to do something." },
  { q: "Which is an exclamation?", o: ["\"I will go tomorrow.\"", "\"Can you help?\"", "\"Open the door.\"", "\"Bravo! Well done!\""], a: "\"Bravo! Well done!\"", e: "Shows strong approval and emotion." },
  { q: "\"Be quiet and listen carefully.\" — Identify the type.", o: ["Statement", "Mixed (two commands)", "Question", "Exclamation"], a: "Mixed (two commands)", e: "Two separate instructions delivered in one sentence." },
  { q: "\"Who are you, and what do you want?\" — Identify the type.", o: ["Statement", "Mixed (two questions)", "Command", "Exclamation"], a: "Mixed (two questions)", e: "Two distinct inquiries merged together." },
  { q: "Which sentence has a strong emotion?", o: ["\"I am happy.\"", "\"What a lovely day!\"", "\"She is reading.\"", "\"Go home.\""], a: "\"What a lovely day!\"", e: "The structure emphasizes feeling over mere fact." },
  { q: "How does a statement typically end?", o: ["?", "!", ".", ","], a: ".", e: "Statements conclude with a full stop." },
  { q: "How does a question typically end?", o: ["?", "!", ".", ";"], a: "?", e: "Questions conclude with a question mark." },
  { q: "How does an exclamation typically end?", o: ["?", "!", ".", ":"], a: "!", e: "Exclamations conclude with an exclamation mark." },
  { q: "A command can end with:", o: ["Only .", "Only !", "Either . or !", "Only ?"], a: "Either . or !", e: "Depending on force, commands use periods or exclamation marks." },
  { q: "\"Stop talking.\" — This is a:", o: ["Statement", "Question", "Command", "Exclamation"], a: "Command", e: "An order given to the listener." },
  { q: "\"He stopped talking.\" — This is a:", o: ["Statement", "Question", "Command", "Exclamation"], a: "Statement", e: "A report of a fact or event." },
  { q: "Which word often appears in exclamations?", o: ["The", "What / How", "Because", "Therefore"], a: "What / How", e: "These function as intensifiers in exclamatory sentences." },
  { q: "\"Good morning!\" — What type?", o: ["Statement", "Question", "Command", "Exclamation/Greeting"], a: "Exclamation/Greeting", e: "A social greeting expressed with emotion." },
  { q: "\"Let's go for a walk.\" — What type?", o: ["Statement", "Question", "Command/Suggestion", "Exclamation"], a: "Command/Suggestion", e: "An inclusive suggestion for action." },
  { q: "Which is NOT a mixed sentence?", o: ["\"Come here and tell me everything.\"", "\"I am tired.\"", "\"Who is he and where is he from?\"", "\"Be calm and think clearly.\""], a: "\"I am tired.\"", e: "A simple, pure statement." },
  { q: "\"May God bless you!\" — What type?", o: ["Statement", "Question", "Command", "Exclamation/Wish"], a: "Exclamation/Wish", e: "An optative sentence showing a prayer or wish." },
  { q: "\"How old are you?\" — What type?", o: ["Statement", "Question", "Command", "Exclamation"], a: "Question", e: "Asks for specific information (age)." },
  { q: "\"I wonder what time it is.\" — What type?", o: ["Statement", "Question", "Command", "Exclamation"], a: "Statement", e: "Though it mentions an inquiry, the main act is a declaration of thought." },
  { q: "\"Please don't go.\" — What type?", o: ["Statement", "Question", "Command/Request", "Exclamation"], a: "Command/Request", e: "A polite request to refrain from an action." },
  { q: "\"What happened here?\" — What type?", o: ["Statement", "Question", "Command", "Exclamation"], a: "Question", e: "Seeks info about past events." },
  { q: "\"Oh! I forgot my keys!\" — What type?", o: ["Statement", "Question", "Command", "Exclamation"], a: "Exclamation", e: "Signals surprise or distress with high feeling." },
  { q: "\"Can you close the door?\" — What type?", o: ["Statement", "Question", "Command", "Exclamation"], a: "Question", e: "Phrased as a question about ability or willingness." },
  { q: "\"She can close the door.\" — What type?", o: ["Statement", "Question", "Command", "Exclamation"], a: "Statement", e: "Declares her ability." },
  { q: "A sentence that gives information is called:", o: ["Interrogative", "Imperative", "Assertive", "Exclamatory"], a: "Assertive", e: "Assertive (or declarative) sentences provide facts." },
  { q: "A sentence that asks for information is called:", o: ["Interrogative", "Imperative", "Assertive", "Exclamatory"], a: "Interrogative", e: "Interrogative sentences are questions." },
  { q: "A sentence that gives an order is called:", o: ["Interrogative", "Imperative", "Assertive", "Exclamatory"], a: "Imperative", e: "Imperative sentences deliver orders or advice." },
  { q: "A sentence that expresses strong emotion is called:", o: ["Interrogative", "Imperative", "Assertive", "Exclamatory"], a: "Exclamatory", e: "Exclamatory sentences focus on feelings." },
  { q: "\"Never give up!\" — What type?", o: ["Statement", "Question", "Command", "Exclamation"], a: "Command", e: "Advice or a motivational instruction." },
  { q: "\"How dare you speak to me like that!\" — What type?", o: ["Statement", "Question", "Command", "Exclamation"], a: "Exclamation", e: "Expresses strong indignation or anger." },
  { q: "\"Listen carefully, understand the problem, and solve it step by step.\" — What type?", o: ["Statement", "Mixed (three commands)", "Question", "Exclamation"], a: "Mixed (three commands)", e: "Three instructions joined together." },
  { q: "Which sentence is purely a statement with no other type mixed in?", o: ["\"The sky is blue.\"", "\"Is the sky blue?\"", "\"Look at the blue sky!\"", "\"What a blue sky!\""], a: "\"The sky is blue.\"", e: "Pure information delivery." },
  { q: "\"Go home now.\" vs \"I am going home now.\" — The difference is:", o: ["Both are statements", "First is command, second is statement", "Both are commands", "First is question, second is statement"], a: "First is command, second is statement", e: "Command orders; statement reports." },
  { q: "\"Did he leave?\" vs \"He left.\" — The difference is:", o: ["Both are questions", "First is question, second is statement", "Both are statements", "First is statement, second is question"], a: "First is question, second is statement", e: "Question asks; statement tells." },
  { q: "Which typically has an interjection (Hurrah, Alas, Oh)?", o: ["Statement", "Question", "Command", "Exclamation"], a: "Exclamation", e: "Interjections mark emotional vocalizations." },
  { q: "\"Bring me that book, please.\" — What type?", o: ["Statement", "Question", "Command/Request", "Exclamation"], a: "Command/Request", e: "A polite imperative." },
  { q: "If a sentence tells you to do something, it is most likely a:", o: ["Statement", "Question", "Command", "Exclamation"], a: "Command", e: "Commands guide the behavior of others." }
];

const m2Data = [
  { q: "In \"Ram said, 'I am happy.'\" — what is the Reporting Verb?", o: ["happy", "am", "said", "Ram"], a: "said", e: "The verb introducing the speech is the reporting verb." },
  { q: "In \"She told him that she was tired.\" — what is the Reported Clause?", o: ["She told him", "that she was tired", "told him that", "She"], a: "that she was tired", e: "The clause containing the message content." },
  { q: "The Reporting Clause contains:", o: ["The exact words spoken", "The speaker and reporting verb", "Only the listener", "Only the time"], a: "The speaker and reporting verb", e: "It identifies the speaker and their mode of speaking." },
  { q: "The Reported Clause contains:", o: ["The speaker", "The exact or modified words spoken", "The reporting verb", "The time of speaking"], a: "The exact or modified words spoken", e: "This is the 'payload' of the message." },
  { q: "Which is the speaker in \"John said, 'I am leaving'\"?", o: ["I", "John", "said", "leaving"], a: "John", e: "The speaker initiates the reporting act." },
  { q: "Which is the listener in \"He told me that he was busy\"?", o: ["He", "me", "busy", "told"], a: "me", e: "Me is the recipient identified in the reporting clause." },
  { q: "How many main elements can change during conversion?", o: ["Three", "Four", "Five", "Six"], a: "Five", e: "TRPT pillars + Quotes/Connectors." },
  { q: "Which element is removed when converting to Indirect Speech?", o: ["Subject", "Verb", "Quotation marks", "Tense"], a: "Quotation marks", e: "Indirect speech removes original punctuation markers." },
  { q: "Which connector typically replaces quotation marks in statements?", o: ["if", "that", "to", "whether"], a: "that", e: "Statements use 'that' as the bridge connector." },
  { q: "What is the reporting verb in \"She asked, 'Where are you going?'\"?", o: ["Where", "asked", "going", "She"], a: "asked", e: "Asked introduces the interrogative report." },
  { q: "The TRPT mantra stands for:", o: ["Time, Reporting, Pronoun, Tense", "Tense, Reporting verb, Pronoun, Time/Place", "Tone, Report, People, Tense", "Tense, Reaction, Purpose, Time"], a: "Tense, Reporting verb, Pronoun, Time/Place", e: "The standard checklist for conversion." },
  { q: "Why do pronouns change in Indirect Speech?", o: ["Grammar rule", "The speaker is now being reported by someone else", "To make it sound formal", "No reason"], a: "The speaker is now being reported by someone else", e: "The reporter refers to the original speaker in the 3rd person." },
  { q: "Why do time words change (e.g., today → that day)?", o: ["Grammar requirement", "Time gap between speaking and reporting", "To make it longer", "They don't change"], a: "Time gap between speaking and reporting", e: "The speaker's 'now' is the reporter's 'then'." },
  { q: "Why does tense shift back (e.g., am → was)?", o: ["The reporting verb is in the past", "To sound polite", "Random rule", "It doesn't shift"], a: "The reporting verb is in the past", e: "Past verbs trigger the alignment of internal tenses." },
  { q: "\"He said to me\" changes to which in Indirect Speech?", o: ["He said me", "He told me", "He asked me", "He spoke me"], a: "He told me", e: "Said to + object standardized as told." },
  { q: "If there is NO listener (\"He said\"), does \"said\" change?", o: ["Yes, to \"told\"", "No, it stays \"said\"", "Yes, to \"asked\"", "Yes, to \"spoke\""], a: "No, it stays \"said\"", e: "Told requires a direct object." },
  { q: "Ram said something on Monday. You report it on Wednesday. Which shift is certain?", o: ["Tense shift", "Time word shift", "Pronoun shift", "All of the above"], a: "All of the above", e: "The delay triggers full perspective shifts." },
  { q: "In \"She says, 'I am ready'\" — what is the time of speaking?", o: ["Past", "Present", "Future", "Unknown"], a: "Present", e: "The verb 'says' indicates the act is current." },
  { q: "Which is NOT one of the five changing elements?", o: ["Quotation marks", "Reporting verb", "Font style", "Tense"], a: "Font style", e: "Font is visual, not grammatical." },
  { q: "The gap between \"time of speaking\" and \"time of reporting\" causes:", o: ["No changes", "Shifts in pronouns, tense, and time/place words", "Only tense shift", "Only pronoun shift"], a: "Shifts in pronouns, tense, and time/place words", e: "This gap defines the need for indirect speech." },
  { q: "What does \"backshift\" mean?", o: ["Moving tenses forward", "Moving tenses one step back in time", "Removing tenses", "Changing pronouns"], a: "Moving tenses one step back in time", e: "Aligning the message with the reporter's timeline." },
  { q: "In Indirect Speech, the exact words are:", o: ["Quoted", "Paraphrased/Modified", "Removed", "Unchanged"], a: "Paraphrased/Modified", e: "Meaning is kept; structure is adapted." },
  { q: "The reporting verb \"said to\" + object becomes:", o: ["said", "told", "asked", "spoke"], a: "told", e: "Standard assertive transformation with object." },
  { q: "If the reporting verb is present tense (says), what happens to the reported speech tense?", o: ["Shifts back", "Stays the same", "Shifts forward", "Doubles"], a: "Stays the same", e: "Present verbs lock internal tenses." },
  { q: "What is the subject in \"The teacher told the students that they should study\"?", o: ["The teacher", "the students", "told", "study"], a: "The teacher", e: "The teacher initiates the communication." },
  { q: "What is the object in \"He told me that he was ill\"?", o: ["He", "me", "told", "ill"], a: "me", e: "Me is the recipient." },
  { q: "Which part tells WHO said it?", o: ["Reported clause", "Reporting clause", "Quotation marks", "Connector"], a: "Reporting clause", e: "It identifies the source of the speech." },
  { q: "Which part tells WHAT was said?", o: ["Reported clause", "Reporting clause", "Speaker", "Listener"], a: "Reported clause", e: "It contains the message content." },
  { q: "\"I\" in Direct Speech (speaker's words) becomes:", o: ["I always", "Follows the subject of reporting verb", "Follows the object", "Stays I"], a: "Follows the subject of reporting verb", e: "Reported pronouns follow original identities." },
  { q: "\"You\" in Direct Speech (listener's words) becomes:", o: ["You always", "Follows the subject", "Follows the object", "Stays you"], a: "Follows the object", e: "The listener's pronouns shift to the reporter's perspective of them." },
  { q: "Third person pronouns (he, she, they) in Direct Speech:", o: ["Always change", "Never change", "Sometimes change", "Become I/we"], a: "Never change", e: "Third parties remain third parties." },
  { q: "If Ram says 'I am happy' and you report it, 'I' becomes:", o: ["I", "he", "you", "we"], a: "he", e: "Ram is a third person relative to you." },
  { q: "If Ram says 'You are smart' to you, and you report it, 'You' becomes:", o: ["you", "I", "he", "we"], a: "I", e: "Since you were the listener, you report it as 'I'." },
  { q: "The five elements are: Quotation marks, Reporting verb, Tense, Pronouns, and:", o: ["Punctuation", "Time & Place words", "Speaker", "Listener"], a: "Time & Place words", e: "The 4th pillar of TRPT." },
  { q: "Which changes ONLY when reporting verb is past?", o: ["Pronouns", "Quotation marks", "Tense", "Reporting verb"], a: "Tense", e: "Tense shift is exclusive to past reports." },
  { q: "The speaker in \"Maya said, 'I love books'\" is:", o: ["I", "Maya", "books", "love"], a: "Maya", e: "Initiator of the statement." },
  { q: "The listener in \"He said to her, 'You are kind'\" is:", o: ["He", "her", "kind", "You"], a: "her", e: "Recipient identified by the object." },
  { q: "In \"I said to the boys, 'You must come'\", the object is:", o: ["I", "the boys", "You", "come"], a: "the boys", e: "Group being addressed." },
  { q: "Reporting structures exist to:", o: ["Make sentences longer", "Report what someone said without using exact quotes", "Confuse students", "Add punctuation"], a: "Report what someone said without using exact quotes", e: "They facilitate storytelling and formal documentation." },
  { q: "Direct Speech is like:", o: ["Paraphrasing", "Quoting", "Summarizing", "Translating"], a: "Quoting", e: "Like a tape recorder of exact sounds." },
  { q: "Indirect Speech is like:", o: ["Quoting", "Paraphrasing with context", "Copying", "Ignoring"], a: "Paraphrasing with context", e: "Conveying meaning within the current scene." },
  { q: "When does NO tense change happen?", o: ["Always", "When reporting verb is past", "When reporting verb is present/future", "Never"], a: "When reporting verb is present/future", e: "Present/Future verbs block the backshift." },
  { q: "\"He will say, 'I am tired'\" — Will the tense of \"am\" change?", o: ["Yes", "No", "Sometimes", "Only if past"], a: "No", e: "Future introductory verb prevents shift." },
  { q: "Context matters. If I report something said 5 seconds ago, should time words change?", o: ["Always change", "May not need to change (context-dependent)", "Never change", "Only pronouns change"], a: "May not need to change (context-dependent)", e: "If the 'now' is still relevant, shifts can be skipped." },
  { q: "The phrase \"Time of Speaking\" means:", o: ["When we report it", "When it was originally said", "Current time", "Future time"], a: "When it was originally said", e: "The original event moment." },
  { q: "The phrase \"Time of Reporting\" means:", o: ["When it was originally said", "When we are NOW reporting it", "Past time", "When we will report"], a: "When we are NOW reporting it", e: "The report event moment." },
  { q: "If speaker and reporter are the same person (I said, \"I am happy\"), does \"I\" change?", o: ["Yes, to he", "No, stays I", "Yes, to we", "Yes, to you"], a: "No, stays I", e: "Identity is identical, no shift needed." },
  { q: "Understanding WHY things change helps you:", o: ["Memorize blindly", "Apply rules logically", "Avoid grammar", "Ignore rules"], a: "Apply rules logically", e: "Logic handles complex context better than memory." },
  { q: "Which is more important to understand first?", o: ["Individual rules", "The framework and WHY changes happen", "Memorizing examples", "Skipping theory"], a: "The framework and WHY changes happen", e: "Context gives purpose to individual mechanics." },
  { q: "The TRPT order helps you:", o: ["Randomly change things", "Systematically check each element", "Skip steps", "Confuse yourself"], a: "Systematically check each element", e: "It ensures all necessary shifts are completed." }
];

const finalize = (data: { q: string, o: string[], a: string, e: string }[], mod: number, cat: string): QuizQuestion[] => 
  data.map((item, idx) => ({
    id: `${mod}.${idx + 1}`,
    category: cat,
    directSpeech: item.q,
    context: `Conceptual Mastery Level ${mod}`,
    options: item.o,
    correctAnswer: item.a,
    explanation: item.e,
    errorType: (mod === 1 ? 'sentence_type' : 'structure') as ErrorType
  }));

export const quizFoundations: Record<string, QuizQuestion[]> = {
  'mod-1': finalize(m1Data, 1, 'Foundations'),
  'mod-2': finalize(m2Data, 2, 'Foundations')
};