
import { QuizQuestion } from './types';

export const quizFoundations: Record<string, QuizQuestion[]> = {
  'mod-1': [
    // --- STATEMENTS (1-10) ---
    { id: '1.1', category: 'Foundations', directSpeech: 'I love playing cricket.', context: 'Identify type', options: ['Question', 'Command', 'Statement', 'Exclamation'], correctAnswer: 'Statement', explanation: 'It declares a simple fact with a period.', errorType: 'sentence_type' },
    { id: '1.2', category: 'Foundations', directSpeech: 'The sun sets in the west.', context: 'Identify type', options: ['Statement', 'Question', 'Command', 'Exclamation'], correctAnswer: 'Statement', explanation: 'A universal truth expressed as a declaration.', errorType: 'sentence_type' },
    { id: '1.3', category: 'Foundations', directSpeech: 'She is a talented musician.', context: 'Identify type', options: ['Statement', 'Command', 'Mixed', 'Question'], correctAnswer: 'Statement', explanation: 'Simple informational sentence.', errorType: 'sentence_type' },
    { id: '1.4', category: 'Foundations', directSpeech: 'Books are our best friends.', context: 'Identify type', options: ['Statement', 'Exclamation', 'Command', 'Question'], correctAnswer: 'Statement', explanation: 'Declares a concept/fact.', errorType: 'sentence_type' },
    { id: '1.5', category: 'Foundations', directSpeech: 'The post-office is closed today.', context: 'Identify type', options: ['Statement', 'Question', 'Command', 'Exclamation'], correctAnswer: 'Statement', explanation: 'Information about a state of being.', errorType: 'sentence_type' },
    { id: '1.6', category: 'Foundations', directSpeech: 'I have finished my homework.', context: 'Identify type', options: ['Statement', 'Command', 'Mixed', 'Exclamation'], correctAnswer: 'Statement', explanation: 'Standard declarative sentence.', errorType: 'sentence_type' },
    { id: '1.7', category: 'Foundations', directSpeech: 'They are playing in the park.', context: 'Identify type', options: ['Statement', 'Question', 'Command', 'Exclamation'], correctAnswer: 'Statement', explanation: 'Observation of an action.', errorType: 'sentence_type' },
    { id: '1.8', category: 'Foundations', directSpeech: 'My mother is a doctor.', context: 'Identify type', options: ['Statement', 'Question', 'Command', 'Exclamation'], correctAnswer: 'Statement', explanation: 'Fact about a person.', errorType: 'sentence_type' },
    { id: '1.9', category: 'Foundations', directSpeech: 'The weather is pleasant today.', context: 'Identify type', options: ['Statement', 'Question', 'Command', 'Exclamation'], correctAnswer: 'Statement', explanation: 'Observation of environment.', errorType: 'sentence_type' },
    { id: '1.10', category: 'Foundations', directSpeech: 'Waffle loves sunflower seeds.', context: 'Identify type', options: ['Statement', 'Question', 'Command', 'Exclamation'], correctAnswer: 'Statement', explanation: 'A declarative fact.', errorType: 'sentence_type' },

    // --- QUESTIONS (11-20) ---
    { id: '1.11', category: 'Foundations', directSpeech: 'Where are you going?', context: 'Identify type', options: ['Question', 'Statement', 'Command', 'Exclamation'], correctAnswer: 'Question', explanation: 'Ends with a question mark and asks for information.', errorType: 'sentence_type' },
    { id: '1.12', category: 'Foundations', directSpeech: 'Do you like apples?', context: 'Identify type', options: ['Statement', 'Question', 'Command', 'Exclamation'], correctAnswer: 'Question', explanation: 'A Yes/No inquiry.', errorType: 'sentence_type' },
    { id: '1.13', category: 'Foundations', directSpeech: 'Have you seen my keys?', context: 'Identify type', options: ['Statement', 'Question', 'Command', 'Exclamation'], correctAnswer: 'Question', explanation: 'Inquiry about an object.', errorType: 'sentence_type' },
    { id: '1.14', category: 'Foundations', directSpeech: 'Why is the sky blue?', context: 'Identify type', options: ['Statement', 'Question', 'Command', 'Exclamation'], correctAnswer: 'Question', explanation: 'A Wh-question.', errorType: 'sentence_type' },
    { id: '1.15', category: 'Foundations', directSpeech: 'Can you help me?', context: 'Identify type', options: ['Statement', 'Question', 'Command', 'Exclamation'], correctAnswer: 'Question', explanation: 'Request phrased as an inquiry.', errorType: 'sentence_type' },
    { id: '1.16', category: 'Foundations', directSpeech: 'Is it raining outside?', context: 'Identify type', options: ['Statement', 'Question', 'Command', 'Exclamation'], correctAnswer: 'Question', explanation: 'Helping verb at the start indicates a question.', errorType: 'sentence_type' },
    { id: '1.17', category: 'Foundations', directSpeech: 'How much does this cost?', context: 'Identify type', options: ['Statement', 'Question', 'Command', 'Exclamation'], correctAnswer: 'Question', explanation: 'Inquiry about price.', errorType: 'sentence_type' },
    { id: '1.18', category: 'Foundations', directSpeech: 'Are they coming to the party?', context: 'Identify type', options: ['Statement', 'Question', 'Command', 'Exclamation'], correctAnswer: 'Question', explanation: 'Group inquiry.', errorType: 'sentence_type' },
    { id: '1.19', category: 'Foundations', directSpeech: 'Will you finish the report?', context: 'Identify type', options: ['Statement', 'Question', 'Command', 'Exclamation'], correctAnswer: 'Question', explanation: 'Future action inquiry.', errorType: 'sentence_type' },
    { id: '1.20', category: 'Foundations', directSpeech: 'Whose bag is this?', context: 'Identify type', options: ['Statement', 'Question', 'Command', 'Exclamation'], correctAnswer: 'Question', explanation: 'Ownership inquiry.', errorType: 'sentence_type' },

    // --- COMMANDS/REQUESTS (21-30) ---
    { id: '1.21', category: 'Foundations', directSpeech: 'Please close the door.', context: 'Identify type', options: ['Statement', 'Exclamation', 'Question', 'Command / Request'], correctAnswer: 'Command / Request', explanation: 'Polite instruction.', errorType: 'sentence_type' },
    { id: '1.22', category: 'Foundations', directSpeech: 'Get out of the room!', context: 'Identify type', options: ['Statement', 'Question', 'Command / Request', 'Exclamation'], correctAnswer: 'Command / Request', explanation: 'Strong instruction (Order).', errorType: 'sentence_type' },
    { id: '1.23', category: 'Foundations', directSpeech: 'Kindly lend me your pen.', context: 'Identify type', options: ['Statement', 'Question', 'Command / Request', 'Exclamation'], correctAnswer: 'Command / Request', explanation: 'Polite request.', errorType: 'sentence_type' },
    { id: '1.24', category: 'Foundations', directSpeech: 'Stand up straight.', context: 'Identify type', options: ['Statement', 'Question', 'Command / Request', 'Exclamation'], correctAnswer: 'Command / Request', explanation: 'Simple instruction.', errorType: 'sentence_type' },
    { id: '1.25', category: 'Foundations', directSpeech: 'Do not make a noise.', context: 'Identify type', options: ['Statement', 'Question', 'Command / Request', 'Exclamation'], correctAnswer: 'Command / Request', explanation: 'Negative instruction.', errorType: 'sentence_type' },
    { id: '1.26', category: 'Foundations', directSpeech: 'Bring me that file.', context: 'Identify type', options: ['Statement', 'Question', 'Command / Request', 'Exclamation'], correctAnswer: 'Command / Request', explanation: 'Direct order.', errorType: 'sentence_type' },
    { id: '1.27', category: 'Foundations', directSpeech: 'Speak the truth.', context: 'Identify type', options: ['Statement', 'Question', 'Command / Request', 'Exclamation'], correctAnswer: 'Command / Request', explanation: 'Advice/instruction.', errorType: 'sentence_type' },
    { id: '1.28', category: 'Foundations', directSpeech: 'Follow the rules.', context: 'Identify type', options: ['Statement', 'Question', 'Command / Request', 'Exclamation'], correctAnswer: 'Command / Request', explanation: 'Formal instruction.', errorType: 'sentence_type' },
    { id: '1.29', category: 'Foundations', directSpeech: 'Be quiet!', context: 'Identify type', options: ['Statement', 'Question', 'Command / Request', 'Exclamation'], correctAnswer: 'Command / Request', explanation: 'Forceful order.', errorType: 'sentence_type' },
    { id: '1.30', category: 'Foundations', directSpeech: 'Let us go for a walk.', context: 'Identify type', options: ['Statement', 'Question', 'Command / Request', 'Exclamation'], correctAnswer: 'Command / Request', explanation: 'Suggestion/Request.', errorType: 'sentence_type' },

    // --- EXCLAMATIONS (31-40) ---
    { id: '1.31', category: 'Foundations', directSpeech: 'What a beautiful day!', context: 'Identify type', options: ['Statement', 'Question', 'Command', 'Exclamation'], correctAnswer: 'Exclamation', explanation: 'Expresses strong surprise/joy.', errorType: 'sentence_type' },
    { id: '1.32', category: 'Foundations', directSpeech: 'Alas! I am ruined!', context: 'Identify type', options: ['Statement', 'Question', 'Command', 'Exclamation'], correctAnswer: 'Exclamation', explanation: 'Expresses deep sorrow.', errorType: 'sentence_type' },
    { id: '1.33', category: 'Foundations', directSpeech: 'Hurrah! We won!', context: 'Identify type', options: ['Statement', 'Question', 'Command', 'Exclamation'], correctAnswer: 'Exclamation', explanation: 'Expresses victory/joy.', errorType: 'sentence_type' },
    { id: '1.34', category: 'Foundations', directSpeech: 'How clever you are!', context: 'Identify type', options: ['Statement', 'Question', 'Command', 'Exclamation'], correctAnswer: 'Exclamation', explanation: 'Expresses amazement.', errorType: 'sentence_type' },
    { id: '1.35', category: 'Foundations', directSpeech: 'Bravo! Well done.', context: 'Identify type', options: ['Statement', 'Question', 'Command', 'Exclamation'], correctAnswer: 'Exclamation', explanation: 'Expresses applause/approval.', errorType: 'sentence_type' },
    { id: '1.36', category: 'Foundations', directSpeech: 'Ouch! That hurts.', context: 'Identify type', options: ['Statement', 'Question', 'Command', 'Exclamation'], correctAnswer: 'Exclamation', explanation: 'Expresses sudden pain.', errorType: 'sentence_type' },
    { id: '1.37', category: 'Foundations', directSpeech: 'Oh! What a surprise.', context: 'Identify type', options: ['Statement', 'Question', 'Command', 'Exclamation'], correctAnswer: 'Exclamation', explanation: 'Expresses wonder.', errorType: 'sentence_type' },
    { id: '1.38', category: 'Foundations', directSpeech: 'Shame! How could you do this?', context: 'Identify type', options: ['Statement', 'Question', 'Command', 'Exclamation'], correctAnswer: 'Exclamation', explanation: 'Expresses contempt/anger.', errorType: 'sentence_type' },
    { id: '1.39', category: 'Foundations', directSpeech: 'Fie! Such a coward.', context: 'Identify type', options: ['Statement', 'Question', 'Command', 'Exclamation'], correctAnswer: 'Exclamation', explanation: 'Expresses disgust.', errorType: 'sentence_type' },
    { id: '1.40', category: 'Foundations', directSpeech: 'Fantastic! I love it.', context: 'Identify type', options: ['Statement', 'Question', 'Command', 'Exclamation'], correctAnswer: 'Exclamation', explanation: 'Expresses enthusiasm.', errorType: 'sentence_type' },

    // --- MIXED (41-50) ---
    { id: '1.41', category: 'Foundations', directSpeech: 'Tell me where you were and what you did.', context: 'Identify type', options: ['Question', 'Statement', 'Mixed', 'Exclamation'], correctAnswer: 'Mixed', explanation: 'Combines a command with embedded questions.', errorType: 'sentence_type' },
    { id: '1.42', category: 'Foundations', directSpeech: 'I am coming; wait for me.', context: 'Identify type', options: ['Statement', 'Command', 'Mixed', 'Question'], correctAnswer: 'Mixed', explanation: 'Statement followed by a command.', errorType: 'sentence_type' },
    { id: '1.43', category: 'Foundations', directSpeech: 'Run! The house is on fire!', context: 'Identify type', options: ['Command', 'Exclamation', 'Mixed', 'Question'], correctAnswer: 'Mixed', explanation: 'A command and an exclamation joined.', errorType: 'sentence_type' },
    { id: '1.44', category: 'Foundations', directSpeech: 'Hello! How are you?', context: 'Identify type', options: ['Greeting', 'Mixed', 'Question', 'Exclamation'], correctAnswer: 'Mixed', explanation: 'A greeting/exclamation plus a question.', errorType: 'sentence_type' },
    { id: '1.45', category: 'Foundations', directSpeech: 'I know you; why did you hide?', context: 'Identify type', options: ['Statement', 'Question', 'Mixed', 'Exclamation'], correctAnswer: 'Mixed', explanation: 'Statement plus a question.', errorType: 'sentence_type' },
    { id: '1.46', category: 'Foundations', directSpeech: 'Stop! Where is your permit?', context: 'Identify type', options: ['Mixed', 'Command', 'Question', 'Exclamation'], correctAnswer: 'Mixed', explanation: 'Forceful command plus question.', errorType: 'sentence_type' },
    { id: '1.47', category: 'Foundations', directSpeech: 'Please wait; he will see you now.', context: 'Identify type', options: ['Mixed', 'Command', 'Statement', 'Question'], correctAnswer: 'Mixed', explanation: 'Request followed by a statement.', errorType: 'sentence_type' },
    { id: '1.48', category: 'Foundations', directSpeech: 'Wow! This is great; can I buy it?', context: 'Identify type', options: ['Mixed', 'Exclamation', 'Question', 'Statement'], correctAnswer: 'Mixed', explanation: 'Exclamation, Statement, and Question.', errorType: 'sentence_type' },
    { id: '1.49', category: 'Foundations', directSpeech: 'Come here; do you know me?', context: 'Identify type', options: ['Mixed', 'Command', 'Question', 'Statement'], correctAnswer: 'Mixed', explanation: 'Command plus question.', errorType: 'sentence_type' },
    { id: '1.50', category: 'Foundations', directSpeech: 'Run quickly and hide behind the tree.', context: 'Identify type', options: ['Statement', 'Command', 'Mixed', 'Exclamation'], correctAnswer: 'Command', explanation: 'Two commands joined are still essentially a compound command.', errorType: 'sentence_type' }
  ],
  'mod-2': [
    // --- REPORTING VERBS (1-10) ---
    { id: '2.1', category: 'Foundations', directSpeech: 'Ram said, "I am happy."', context: 'Identify Reporting Verb', options: ['happy', 'am', 'said', 'Ram'], correctAnswer: 'said', explanation: 'The verb used to introduce the speaker.', errorType: 'structure' },
    { id: '2.2', category: 'Foundations', directSpeech: 'She asked me if I was tired.', context: 'Identify Reporting Verb', options: ['asked', 'me', 'tired', 'was'], correctAnswer: 'asked', explanation: 'Used for questions.', errorType: 'structure' },
    { id: '2.3', category: 'Foundations', directSpeech: 'The teacher told the class to be quiet.', context: 'Identify Reporting Verb', options: ['class', 'quiet', 'told', 'be'], correctAnswer: 'told', explanation: 'Reporting verb with an object.', errorType: 'structure' },
    { id: '2.4', category: 'Foundations', directSpeech: 'He inquired about the time.', context: 'Identify Reporting Verb', options: ['time', 'inquired', 'about', 'He'], correctAnswer: 'inquired', explanation: 'Formal reporting verb.', errorType: 'structure' },
    { id: '2.5', category: 'Foundations', directSpeech: 'They shouted for help.', context: 'Identify Reporting Verb', options: ['help', 'shouted', 'for', 'They'], correctAnswer: 'shouted', explanation: 'Reporting verb indicating volume/tone.', errorType: 'structure' },
    { id: '2.6', category: 'Foundations', directSpeech: 'The doctor advised him to rest.', context: 'Identify Reporting Verb', options: ['rest', 'advised', 'doctor', 'him'], correctAnswer: 'advised', explanation: 'Verb indicating suggestion.', errorType: 'structure' },
    { id: '2.7', category: 'Foundations', directSpeech: 'She requested a pen.', context: 'Identify Reporting Verb', options: ['pen', 'requested', 'a', 'She'], correctAnswer: 'requested', explanation: 'Verb for requests.', errorType: 'structure' },
    { id: '2.8', category: 'Foundations', directSpeech: 'Mother warned the child.', context: 'Identify Reporting Verb', options: ['child', 'warned', 'Mother', 'the'], correctAnswer: 'warned', explanation: 'Verb for safety/alarm.', errorType: 'structure' },
    { id: '2.9', category: 'Foundations', directSpeech: 'He replied that he was busy.', context: 'Identify Reporting Verb', options: ['replied', 'busy', 'that', 'He'], correctAnswer: 'replied', explanation: 'Verb used for response.', errorType: 'structure' },
    { id: '2.10', category: 'Foundations', directSpeech: 'I explained the rule.', context: 'Identify Reporting Verb', options: ['rule', 'explained', 'the', 'I'], correctAnswer: 'explained', explanation: 'Verb used for clarification.', errorType: 'structure' },

    // --- REPORTED CLAUSE (11-20) ---
    { id: '2.11', category: 'Foundations', directSpeech: 'She told him that she was tired.', context: 'Identify Reported Clause', options: ['She told him', 'that she was tired', 'told him that', 'She'], correctAnswer: 'that she was tired', explanation: 'The content of what was said.', errorType: 'structure' },
    { id: '2.12', category: 'Foundations', directSpeech: 'He said he lived here.', context: 'Identify Reported Clause', options: ['He said', 'he lived here', 'lived here', 'he'], correctAnswer: 'he lived here', explanation: 'The reported statement.', errorType: 'structure' },
    { id: '2.13', category: 'Foundations', directSpeech: 'I asked if it was true.', context: 'Identify Reported Clause', options: ['if it was true', 'I asked', 'it was true', 'asked if'], correctAnswer: 'if it was true', explanation: 'The indirect question clause.', errorType: 'structure' },
    { id: '2.14', category: 'Foundations', directSpeech: 'The judge ordered to release him.', context: 'Identify Reported Clause', options: ['to release him', 'Judge ordered', 'release him', 'ordered to'], correctAnswer: 'to release him', explanation: 'The imperative reported clause.', errorType: 'structure' },
    { id: '2.15', category: 'Foundations', directSpeech: 'She suggested that we should go.', context: 'Identify Reported Clause', options: ['suggested that', 'that we should go', 'we should go', 'She suggested'], correctAnswer: 'that we should go', explanation: 'The suggestion content.', errorType: 'structure' },
    { id: '2.16', category: 'Foundations', directSpeech: 'He told me I was late.', context: 'Identify Reported Clause', options: ['I was late', 'He told me', 'was late', 'me'], correctAnswer: 'I was late', explanation: 'The core message.', errorType: 'structure' },
    { id: '2.17', category: 'Foundations', directSpeech: 'They claimed that the car was theirs.', context: 'Identify Reported Clause', options: ['They claimed', 'that the car was theirs', 'car was theirs', 'claimed that'], correctAnswer: 'that the car was theirs', explanation: 'The claim being reported.', errorType: 'structure' },
    { id: '2.18', category: 'Foundations', directSpeech: 'She wondered why he left.', context: 'Identify Reported Clause', options: ['wondered why', 'why he left', 'he left', 'She wondered'], correctAnswer: 'why he left', explanation: 'The indirect Wh-question.', errorType: 'structure' },
    { id: '2.19', category: 'Foundations', directSpeech: 'He promised to help me.', context: 'Identify Reported Clause', options: ['to help me', 'He promised', 'help me', 'promised to'], correctAnswer: 'to help me', explanation: 'The promise action.', errorType: 'structure' },
    { id: '2.20', category: 'Foundations', directSpeech: 'I noted that it was raining.', context: 'Identify Reported Clause', options: ['noted that', 'that it was raining', 'it was raining', 'I noted'], correctAnswer: 'that it was raining', explanation: 'The observation report.', errorType: 'structure' },

    // --- TRPT PILLARS (21-30) ---
    { id: '2.21', category: 'Foundations', directSpeech: 'Elements of transformation', context: 'Identify all five changes', options: ['Quotes, Verb, Tense, Pronouns, Punctuation', 'Quotes & connector, Verb, Tense, Pronouns, Time & Place', 'Speaker, Listener, Tense, Pronouns, Verb', 'Quotes, Tense, Pronouns, Time, Font'], correctAnswer: 'Quotes & connector, Verb, Tense, Pronouns, Time & Place', explanation: 'These are the 5 pillars of the TRPT Mantra.', errorType: 'general' },
    { id: '2.22', category: 'Foundations', directSpeech: 'The "T" in TRPT stands for...', context: 'Identify Pillar', options: ['Tone', 'Time', 'Tense', 'Today'], correctAnswer: 'Tense', explanation: 'Refers to the backshift of verbs.', errorType: 'general' },
    { id: '2.23', category: 'Foundations', directSpeech: 'The "R" in TRPT stands for...', context: 'Identify Pillar', options: ['Reporting Verb', 'Recorded Speech', 'Rule', 'Ram'], correctAnswer: 'Reporting Verb', explanation: 'The verb that introduces the speech.', errorType: 'general' },
    { id: '2.24', category: 'Foundations', directSpeech: 'The "P" in TRPT stands for...', context: 'Identify Pillar', options: ['Place', 'Punctuation', 'Pronouns', 'Post'], correctAnswer: 'Pronouns', explanation: 'Refers to the shift in identity (I/You).', errorType: 'general' },
    { id: '2.25', category: 'Foundations', directSpeech: 'The last "T" in TRPT refers to...', context: 'Identify Pillar', options: ['Total', 'Time & Place', 'Tense', 'Tone'], correctAnswer: 'Time & Place', explanation: 'Refers to the shift from near words to far words.', errorType: 'general' },
    { id: '2.26', category: 'Foundations', directSpeech: 'Which pillar handles is -> was?', context: 'Identify Pillar', options: ['Tense', 'Reporting Verb', 'Pronouns', 'Time'], correctAnswer: 'Tense', explanation: 'Verb shifts fall under Tense.', errorType: 'general' },
    { id: '2.27', category: 'Foundations', directSpeech: 'Which pillar handles I -> He?', context: 'Identify Pillar', options: ['Tense', 'Reporting Verb', 'Pronouns', 'Time'], correctAnswer: 'Pronouns', explanation: 'Subject shifts fall under Pronouns.', errorType: 'general' },
    { id: '2.28', category: 'Foundations', directSpeech: 'Which pillar handles said to -> told?', context: 'Identify Pillar', options: ['Tense', 'Reporting Verb', 'Pronouns', 'Time'], correctAnswer: 'Reporting Verb', explanation: 'Intro verb shifts fall under Reporting Verb.', errorType: 'general' },
    { id: '2.29', category: 'Foundations', directSpeech: 'Which pillar handles now -> then?', context: 'Identify Pillar', options: ['Tense', 'Reporting Verb', 'Pronouns', 'Time & Place'], correctAnswer: 'Time & Place', explanation: 'Temporal shifts fall under Time & Place.', errorType: 'general' },
    { id: '2.30', category: 'Foundations', directSpeech: 'Which pillar handles here -> there?', context: 'Identify Pillar', options: ['Tense', 'Reporting Verb', 'Pronouns', 'Time & Place'], correctAnswer: 'Time & Place', explanation: 'Spatial shifts fall under Time & Place.', errorType: 'general' },

    // --- CASE STUDIES (31-50) ---
    { id: '2.31', category: 'Foundations', directSpeech: 'Monday to Wednesday reporting', context: 'Identify necessary shifts', options: ['Only tense', 'Only pronoun', 'Tense, pronoun, and time/place', 'Only time/place'], correctAnswer: 'Tense, pronoun, and time/place', explanation: 'Time gap requires full TRPT coverage.', errorType: 'general' },
    { id: '2.32', category: 'Foundations', directSpeech: 'Reporting in the same room', context: 'Identify shift', options: ['Here stays Here', 'Here becomes There', 'There becomes Here', 'No change'], correctAnswer: 'Here becomes There', explanation: 'Grammar assumes distance in indirect speech even if physically present.', errorType: 'general' },
    { id: '2.33', category: 'Foundations', directSpeech: 'Reporting a truth (e.g., Earth is round)', context: 'Identify shift', options: ['Full Backshift', 'No Tense Change', 'Only Pronoun Change', 'Only Verb Change'], correctAnswer: 'No Tense Change', explanation: 'Universal truths are exempt from backshift.', errorType: 'no_change' },
    { id: '2.34', category: 'Foundations', directSpeech: 'Reporting a question to a listener', context: 'Identify Verb', options: ['told', 'said', 'asked', 'replied'], correctAnswer: 'asked', explanation: 'Questions require an inquiry verb.', errorType: 'reporting_verb' },
    { id: '2.35', category: 'Foundations', directSpeech: 'Reporting a command to a servant', context: 'Identify Verb', options: ['requested', 'asked', 'ordered', 'wondered'], correctAnswer: 'ordered', explanation: 'Commands use authoritative verbs.', errorType: 'reporting_verb' },
    { id: '2.36', category: 'Foundations', directSpeech: 'If reporting verb is "says"', context: 'Identify shift', options: ['Tense shifts back', 'No Tense shift', 'Time shifts forward', 'No pronoun shift'], correctAnswer: 'No Tense shift', explanation: 'Present reporting verbs block backshift.', errorType: 'no_change' },
    { id: '2.37', category: 'Foundations', directSpeech: 'Direct: I am here now.', context: 'Predict 3 shifts', options: ['he was there then', 'he is there now', 'I was there then', 'he was here then'], correctAnswer: 'he was there then', explanation: 'Pronoun (I->he), Tense (am->was), Time/Place (here/now->there/then).', errorType: 'general' },
    { id: '2.38', category: 'Foundations', directSpeech: 'The "PRO Rule" handles...', context: 'Identify purpose', options: ['Tense', 'Pronouns', 'Place', 'Order'], correctAnswer: 'Pronouns', explanation: 'Specifically 1st and 2nd person shifts.', errorType: 'pronoun' },
    { id: '2.39', category: 'Foundations', directSpeech: 'The "SQCEM Trick" handles...', context: 'Identify purpose', options: ['Tense', 'Reporting Verb', 'Pronouns', 'Sentence Identification'], correctAnswer: 'Sentence Identification', explanation: 'Identifying type before conversion.', errorType: 'sentence_type' },
    { id: '2.40', category: 'Foundations', directSpeech: 'Indirect speech removal', context: 'Identify target', options: ['Full stops', 'Quotation marks', 'Pronouns', 'Verbs'], correctAnswer: 'Quotation marks', explanation: 'Quotes are never kept in indirect speech.', errorType: 'structure' },
    { id: '2.41', category: 'Foundations', directSpeech: 'Indirect speech addition', context: 'Identify target', options: ['Connector (that/if/to)', 'Question mark', 'Exclamation mark', 'Direct quotes'], correctAnswer: 'Connector (that/if/to)', explanation: 'Used to bridge reporting and reported clauses.', errorType: 'structure' },
    { id: '2.42', category: 'Foundations', directSpeech: 'Backshift: "did" becomes...', context: 'Predict tense', options: ['done', 'had done', 'do', 'will do'], correctAnswer: 'had done', explanation: 'Past Simple shifts to Past Perfect.', errorType: 'tense' },
    { id: '2.43', category: 'Foundations', directSpeech: 'Backshift: "will" becomes...', context: 'Predict tense', options: ['would', 'shall', 'should', 'can'], correctAnswer: 'would', explanation: 'Future modals shift to past form.', errorType: 'tense' },
    { id: '2.44', category: 'Foundations', directSpeech: 'Backshift: "can" becomes...', context: 'Predict tense', options: ['could', 'may', 'might', 'must'], correctAnswer: 'could', explanation: 'Ability modal shifts to past form.', errorType: 'tense' },
    { id: '2.45', category: 'Foundations', directSpeech: 'Backshift: "have" becomes...', context: 'Predict tense', options: ['has', 'had', 'having', 'will have'], correctAnswer: 'had', explanation: 'Present Perfect shifts to Past Perfect.', errorType: 'tense' },
    { id: '2.46', category: 'Foundations', directSpeech: 'Backshift: "saw" becomes...', context: 'Predict tense', options: ['see', 'had seen', 'sees', 'seen'], correctAnswer: 'had seen', explanation: 'Past Simple shifts to Past Perfect.', errorType: 'tense' },
    { id: '2.47', category: 'Foundations', directSpeech: 'Backshift: "is writing" becomes...', context: 'Predict tense', options: ['wrote', 'was writing', 'had written', 'had been writing'], correctAnswer: 'was writing', explanation: 'Present Continuous shifts to Past Continuous.', errorType: 'tense' },
    { id: '2.48', category: 'Foundations', directSpeech: 'Backshift: "was writing" becomes...', context: 'Predict tense', options: ['wrote', 'had been writing', 'is writing', 'had written'], correctAnswer: 'had been writing', explanation: 'Past Continuous shifts to Past Perfect Continuous.', errorType: 'tense' },
    { id: '2.49', category: 'Foundations', directSpeech: 'Backshift: "must" becomes...', context: 'Predict tense', options: ['should', 'had to', 'might', 'will'], correctAnswer: 'had to', explanation: 'Obligation modal usually shifts to had to.', errorType: 'tense' },
    { id: '2.50', category: 'Foundations', directSpeech: 'Final Exam Readiness', context: 'Check final pillar', options: ['Formatting', 'Tone consistency', 'Logical flow', 'All of TRPT'], correctAnswer: 'All of TRPT', explanation: 'Mastering all 5 pillars ensures 100% accuracy.', errorType: 'general' }
  ]
};
