
import { QuizQuestion } from './types';

export const quizAdvanced: Record<string, QuizQuestion[]> = {
  'mod-23': [
    { id: '23.1', category: 'Advanced', directSpeech: 'Type 3 Conditional', context: 'Rule', options: ['shift back', 'nothing changes', 'had known -> have known', 'would have -> will have'], correctAnswer: 'Nothing changes — they are already in past perfect.', explanation: 'Past perfect cannot shift further back.', errorType: 'no_change' },
    { id: '23.2', category: 'Advanced', directSpeech: 'If it rains, I will not go.', context: 'Type 1 Conditional', options: ['if it rained, he would not go', 'if it rains, he will not go', 'if it rained, he will not go', 'told that if it rained...'], correctAnswer: 'He said that if it rained, he would not go.', explanation: 'Type 1 conditional backshifts.', errorType: 'tense' },
    { id: '23.3', category: 'Advanced', directSpeech: 'If I were rich, I would help.', context: 'Type 2 Conditional', options: ['if she was rich', 'if she were rich', 'could help', 'told that she were'], correctAnswer: 'She said that if she were rich, she would help the poor.', explanation: 'Subjunctive "were" stays "were".', errorType: 'no_change' },
    { id: '23.4', category: 'Advanced', directSpeech: 'If I were the teacher...', context: 'Identify error', options: ['No error', '"was" is wrong (subjunctive)', 'would -> could', 'the -> a'], correctAnswer: '"was" is wrong. "Were" must stay as "were" because it is subjunctive mood (expressing an unreal/hypothetical condition), not actual past tense. It should not be shifted.', explanation: 'Preserve subjunctive mood.', errorType: 'no_change' }
  ],
  'mod-24': [
    { id: '24.1', category: 'Advanced', directSpeech: 'Mixed Strategy', context: 'Rule', options: ['convert at once', 'break into parts', 'only first clause', 'ignore second'], correctAnswer: 'Break it into parts, identify each type, then convert each part separately.', explanation: 'Mixed sentences need granular analysis.', errorType: 'general' },
    { id: '24.2', category: 'Advanced', directSpeech: 'Be quiet and listen.', context: 'Double command', options: ['told them to', 'urged them to', 'asked them to', 'said to'], correctAnswer: 'He urged them to be quiet and listen to his words.', explanation: 'Choose reporting verb matching tone.', errorType: 'reporting_verb' },
    { id: '24.3', category: 'Advanced', directSpeech: 'I can\'t come because I am busy now.', context: 'Mixed statement', options: ['couldn\'t... was busy then', 'can\'t... is busy now', 'couldn\'t... is busy then', 'told that she couldn\'t...'], correctAnswer: 'She said that she couldn\'t come because she was busy then.', explanation: 'Both clauses backshift.', errorType: 'tense' },
    { id: '24.4', category: 'Advanced', directSpeech: 'The meeting has been postponed...', context: 'Complex mixed', options: ['had been... following week... should', 'has been...', 'told that...', 'by now'], correctAnswer: 'The manager said that the meeting had been postponed to the following week, and that everyone should prepare their reports by then.', explanation: 'Full TRPT coverage.', errorType: 'time_place' }
  ],
  'mod-25': [
    { id: '25.1', category: 'Advanced', directSpeech: 'Quote within quote', context: 'Rule', options: ['Keep both', 'Flatten both', 'Remove outer only', 'Remove inner only'], correctAnswer: 'Flatten both layers into one smooth Indirect sentence.', explanation: 'Indirect speech should be a seamless report.', errorType: 'structure' },
    { id: '25.2', category: 'Advanced', directSpeech: 'My teacher told me, "Work hard."', context: 'Nested imperative', options: ['teacher told him', 'teacher had told him', 'my teacher told me', 'told that his teacher had'], correctAnswer: 'He said that his teacher had told him to work hard.', explanation: 'Backshift "told" and convert inner command.', errorType: 'tense' },
    { id: '25.3', category: 'Advanced', directSpeech: 'My mother asked, "Have you eaten?"', context: 'Nested question', options: ['mother asked her if', 'mother had asked her if', 'whether she eats', 'told that her mother had'], correctAnswer: 'She said that her mother had asked her if she had eaten.', explanation: 'Double backshift.', errorType: 'tense' },
    { id: '25.4', category: 'Advanced', directSpeech: 'Complex nested announcement', context: 'Advanced nested', options: ['had announced that... had been... following week', 'announced... has been...', 'had announced... and all students had to', 'told that...'], correctAnswer: 'He said that the teacher had announced that the exam had been postponed to the following week, and that all students must prepare.', explanation: 'Full TRPT and nesting control.', errorType: 'tense' }
  ],
  'mod-26': [
    { id: '26.1', category: 'Advanced', directSpeech: '"I know her address," said Gopal.', context: 'Identify location', options: ['beginning', 'middle', 'end', 'missing'], correctAnswer: 'At the end', explanation: 'Reporting clause follows speech.', errorType: 'structure' },
    { id: '26.2', category: 'Advanced', directSpeech: '"I know her address," said Gopal.', context: 'End-split conversion', options: ['Gopal said that he knew', 'Gopal said that I knew', 'Gopal told that', 'Gopal asked that'], correctAnswer: 'Gopal said that he knew her address.', explanation: 'Reporting clause moves to front.', errorType: 'structure' },
    { id: '26.3', category: 'Advanced', directSpeech: '"I am," he said, "very tired."', context: 'Mid-split conversion', options: ['he is', 'I am', 'he was', 'direct speech'], correctAnswer: 'He said that he was very tired.', explanation: 'Reporting clause moves to front.', errorType: 'structure' },
    { id: '26.4', category: 'Advanced', directSpeech: '"I have done it," she said proudly...', context: 'Complex parenthetical', options: ['proudly said she had done it... very happy', 'I had done it...', 'proudly told that...', 'has done it...'], correctAnswer: 'She proudly said that she had done it all by myself, and that she was very happy about it.', explanation: 'Smooth narrative report.', errorType: 'tense' }
  ]
};
