
import { QuizQuestion } from './types';

export const quizStatements: Record<string, QuizQuestion[]> = {
  'mod-3': [
    { id: '3.1', category: 'Statements', directSpeech: 'Rajan said, "I am ill."', context: 'Basic conversion', options: ['Rajan said that I am ill.', 'Rajan said that he was ill.', 'Rajan told that he was ill.', 'Rajan said that he is ill.'], correctAnswer: 'Rajan said that he was ill.', explanation: 'Tense shifts to past; I shifts to he.', errorType: 'tense' },
    { id: '3.2', category: 'Statements', directSpeech: 'She said, "I have finished my work."', context: 'Perfect tense', options: ['She said that she has finished her work.', 'She said that I had finished my work.', 'She said that she had finished her work.', 'She told that she had finished her work.'], correctAnswer: 'She said that she had finished her work.', explanation: 'Present perfect shifts to past perfect.', errorType: 'tense' },
    { id: '3.3', category: 'Statements', directSpeech: 'She said, "I was sleeping when the phone rang."', context: 'Past continuous', options: ['She said that she was sleeping...', 'She said that she had been sleeping...', 'She said that I was sleeping...', 'She told that she had been sleeping...'], correctAnswer: 'She said that she had been sleeping...', explanation: 'Past continuous shifts to past perfect continuous.', errorType: 'tense' },
    { id: '3.4', category: 'Statements', directSpeech: 'They said, "We are very happy."', context: 'Identify error', options: ['"said" should be "told"', '"that" should not be there', '"we" should be "they"', '"were" should be "are"'], correctAnswer: '"we" should be "they"', explanation: 'Pronoun must match the subject.', errorType: 'pronoun' }
  ],
  'mod-4': [
    { id: '4.1', category: 'Statements', directSpeech: 'He said to me, "You are brilliant."', context: 'Object conversion', options: ['He said to me that I was brilliant.', 'He told me that you were brilliant.', 'He told me that I was brilliant.', 'He asked me that I was brilliant.'], correctAnswer: 'He told me that I was brilliant.', explanation: 'said to -> told; you -> I.', errorType: 'reporting_verb' },
    { id: '4.2', category: 'Statements', directSpeech: 'I said to the boys, "You should do your duty."', context: 'Object conversion', options: ['I told the boys that you should...', 'I told the boys that they should...', 'I said to the boys that they should...', 'I told the boys that I should...'], correctAnswer: 'I told the boys that they should...', explanation: 'You -> they; your -> their.', errorType: 'pronoun' },
    { id: '4.3', category: 'Statements', directSpeech: 'Rama said to the girl, "I know you and your aunt."', context: 'Mixed pronouns', options: ['Rama told the girl that he knew you...', 'Rama told the girl that I knew her...', 'Rama told the girl that he knew her and her aunt.', 'Rama said to the girl that he knew...'], correctAnswer: 'Rama told the girl that he knew her and her aunt.', explanation: 'I -> he; you -> her.', errorType: 'pronoun' },
    { id: '4.4', category: 'Statements', directSpeech: 'He said to me, "I don\'t believe you, but I believe him."', context: 'Complex pronouns', options: ['He told me that he didn\'t believe me, but he believed him.', 'He told me that I didn\'t believe him...', 'He told me that he didn\'t believe you...', 'He said to me that he didn\'t believe me...'], correctAnswer: 'He told me that he didn\'t believe me, but he believed him.', explanation: 'Tense backshifts and pronoun alignment.', errorType: 'tense' }
  ],
  'mod-5': [
    { id: '5.1', category: 'Statements', directSpeech: 'tomorrow', context: 'Time shift', options: ['that day', 'the next day', 'yesterday', 'then'], correctAnswer: 'the next day', explanation: 'Tomorrow becomes the next/following day.', errorType: 'time_place' },
    { id: '5.2', category: 'Statements', directSpeech: 'She said, "I will finish it today."', context: 'Today shift', options: ['She said that she would finish it today.', 'She said that she will finish it that day.', 'She said that she would finish it that day.', 'She told that she would finish it that day.'], correctAnswer: 'She said that she would finish it that day.', explanation: 'will -> would; today -> that day.', errorType: 'time_place' },
    { id: '5.3', category: 'Statements', directSpeech: 'He said, "I met him two days ago."', context: 'Ago shift', options: ['He said that he met him...', 'He said that he had met him two days before.', 'He said that he had met him two days ago.', 'He said that he meets him...'], correctAnswer: 'He said that he had met him two days before.', explanation: 'met -> had met; ago -> before.', errorType: 'time_place' },
    { id: '5.4', category: 'Statements', directSpeech: 'Yesterday/Tomorrow mix', context: 'Complex time shift', options: ['She said she had seen her the previous morning...', 'She said she saw her yesterday morning...', 'She had seen her the previous and will see...', 'She sees her the previous and would see...'], correctAnswer: 'She said she had seen her the previous morning and she would see her again the next evening.', explanation: 'Full TRPT coverage.', errorType: 'time_place' }
  ],
  'mod-6': [
    { id: '6.1', category: 'Statements', directSpeech: 'here', context: 'Place shift', options: ['this', 'then', 'there', 'that'], correctAnswer: 'there', explanation: 'Near becomes far.', errorType: 'time_place' },
    { id: '6.2', category: 'Statements', directSpeech: 'He said, "I bought this book."', context: 'This shift', options: ['He said that he bought this book.', 'He said that he had bought that book.', 'He said that he had bought this book.', 'He told that he had bought that book.'], correctAnswer: 'He said that he had bought that book.', explanation: 'this -> that; bought -> had bought.', errorType: 'time_place' },
    { id: '6.3', category: 'Statements', directSpeech: 'These are my notes and this is my pen.', context: 'Plural place shift', options: ['Those were her notes and that was her pen.', 'These were her notes and this was...', 'Those are her notes and that is...', 'Those were her notes and that was...'], correctAnswer: 'She said that those were her notes and that was her pen.', explanation: 'These -> those; this -> that.', errorType: 'time_place' },
    { id: '6.4', category: 'Statements', directSpeech: 'Come here and bring this file with you.', context: 'Motion shift', options: ['Come there and bring that file...', 'Go there and take that file with me.', 'Go here and bring this file...', 'Come here and take that file...'], correctAnswer: 'He told me to go there and take that file with me.', explanation: 'Come/bring often become go/take in reports.', errorType: 'time_place' }
  ],
  'mod-7': [
    { id: '7.1', category: 'Statements', directSpeech: 'can', context: 'Modal shift', options: ['will', 'could', 'should', 'might'], correctAnswer: 'could', explanation: 'Can shifts to could.', errorType: 'tense' },
    { id: '7.2', category: 'Statements', directSpeech: 'He said, "It may rain tomorrow."', context: 'May shift', options: ['It may rain the next day.', 'It might rain tomorrow.', 'It might rain the next day.', 'It could rain the next day.'], correctAnswer: 'He said that it might rain the next day.', explanation: 'may -> might; tomorrow -> next day.', errorType: 'tense' },
    { id: '7.3', category: 'Statements', directSpeech: 'I could not find my keys yesterday.', context: 'Could shift', options: ['couldn\'t find her keys the previous day.', 'could not find her keys the previous day.', 'can not find...', 'might not find...'], correctAnswer: 'She said that she could not find her keys the previous day.', explanation: 'Could stays could; yesterday shifts.', errorType: 'time_place' },
    { id: '7.4', category: 'Statements', directSpeech: 'I must go now.', context: 'Must shift error', options: ['"should" is correct', '"must" -> "had to"', '"now" no change', '"said" -> "told"'], correctAnswer: '"must" can become "must" or "had to" — not "should". "Should" is the past form of "shall", not "must".', explanation: 'Must has specific backshifts.', errorType: 'tense' }
  ],
  'mod-8': [
    { id: '8.1', category: 'Statements', directSpeech: 'says', context: 'Present reporting verb', options: ['Changes one step back', 'Does not change at all', 'Changes two steps back', 'Only if modal'], correctAnswer: 'Does not change at all', explanation: 'No time gap = no shift.', errorType: 'no_change' },
    { id: '8.2', category: 'Statements', directSpeech: 'The servant says, "Tea is ready."', context: 'Present shift', options: ['tea was ready', 'tea is ready', 'tea is ready (told)', 'tea is ready (said)'], correctAnswer: 'The servant says that tea is ready.', explanation: 'No tense change if reporting verb is present.', errorType: 'no_change' },
    { id: '8.3', category: 'Statements', directSpeech: 'She tells me, "I have finished my homework."', context: 'Tells shift', options: ['had finished', 'has finished', 'has finished (told)', 'I have finished'], correctAnswer: 'She tells me that she has finished her homework.', explanation: 'Tense stays; pronoun shifts.', errorType: 'no_change' },
    { id: '8.4', category: 'Statements', directSpeech: 'Correct pair conversion', context: 'Present/Future reporting', options: ['He says... was tired', 'He says... is tired / She will say... is tired', 'He says... is tired / She will say... was', 'He says... was / She will say... is'], correctAnswer: 'He says, "I am tired." → He says that he is tired. / She will say, "I am tired." → She will say that she is tired.', explanation: 'Present/Future reporting verbs block backshift.', errorType: 'no_change' }
  ],
  'mod-9': [
    { id: '9.1', category: 'Statements', directSpeech: 'The sun rises in the east.', context: 'Universal truth', options: ['rose', 'rises', 'had risen', 'was rising'], correctAnswer: 'rises', explanation: 'Universal truths keep present tense.', errorType: 'no_change' },
    { id: '9.2', category: 'Statements', directSpeech: 'Water boils at 100°C.', context: 'Scientific fact', options: ['boiled', 'boils', 'boils (told)', 'is boiling'], correctAnswer: 'He said that water boils at 100°C.', explanation: 'Tense remains present.', errorType: 'no_change' },
    { id: '9.3', category: 'Statements', directSpeech: 'Earth revolves', context: 'Identify truth', options: ['Going to market', 'Cooking dinner', 'The earth revolves around the sun.', 'Studying for exam'], correctAnswer: 'The earth revolves around the sun.', explanation: 'Permanent geographical fact.', errorType: 'no_change' },
    { id: '9.4', category: 'Statements', directSpeech: 'Gravity keeps us on the earth.', context: 'Identify error', options: ['Nothing wrong', '"kept" is wrong (universal truth)', '"said" -> "told"', '"us" -> "them"'], correctAnswer: '"kept" is wrong because gravity keeping us on the earth is a universal/scientific truth, so "keeps" should be retained.', explanation: 'Backshift is prohibited for universal laws.', errorType: 'no_change' }
  ]
};
