
import { QuizQuestion } from './types';

export const quizQuestions: Record<string, QuizQuestion[]> = {
  'mod-10': [
    { id: '10.1', category: 'Questions', directSpeech: 'Yes/No Connector', context: 'Rule', options: ['that', 'where', 'if / whether', 'to'], correctAnswer: 'if / whether', explanation: 'Yes/no questions use if or whether.', errorType: 'structure' },
    { id: '10.2', category: 'Questions', directSpeech: 'Do you know the way?', context: 'Basic Yes/No', options: ['if I know', 'if I knew', 'if I knew (told)', 'that I knew'], correctAnswer: 'He asked me if I knew the way.', explanation: 'Flipped order; backshifted tense.', errorType: 'structure' },
    { id: '10.3', category: 'Questions', directSpeech: 'Have you finished your homework?', context: 'Present Perfect Yes/No', options: ['if you had finished', 'whether we had finished', 'that we had finished', 'if we had finished (told)'], correctAnswer: 'The teacher asked whether we had finished our homework.', explanation: 'Order flip: (HV+S) -> (S+HV).', errorType: 'structure' },
    { id: '10.4', category: 'Questions', directSpeech: 'Are you coming to the party?', context: 'Identify error', options: ['whether -> if', 'is -> was', 'him -> her', 'no error'], correctAnswer: '"is coming" should be "was coming" — the tense must shift back because the reporting verb is past.', explanation: 'Reporting verb "asked" (past) requires backshift.', errorType: 'tense' }
  ],
  'mod-11': [
    { id: '11.1', category: 'Questions', directSpeech: 'Will you come to the party?', context: 'Will shift', options: ['if he will come', 'if he would come', 'that he would come', 'if he would come (told)'], correctAnswer: 'She asked if he would come to the party.', explanation: 'will -> would.', errorType: 'tense' },
    { id: '11.2', category: 'Questions', directSpeech: 'Can you help me?', context: 'Can shift', options: ['if I can help', 'if I could help me', 'if I could help him', 'if I could help him (told)'], correctAnswer: 'He asked me if I could help him.', explanation: 'can -> could; me -> him.', errorType: 'pronoun' },
    { id: '11.3', category: 'Questions', directSpeech: 'Shall I open the window?', context: 'Shall shift', options: ['if he shall', 'if he should', 'if I should', 'if he should (told)'], correctAnswer: 'He asked if he should open the window.', explanation: 'shall -> should.', errorType: 'tense' },
    { id: '11.4', category: 'Questions', directSpeech: 'Double Modal Question', context: 'Complex Yes/No', options: ['if he would... and if he could', 'if he would... and if he can', 'if he would... (told)', 'whether he minds... and if he could'], correctAnswer: 'She asked him if he would mind closing the door, and if he could also turn off the light.', explanation: 'Both modals backshift.', errorType: 'tense' }
  ],
  'mod-12': [
    { id: '12.1', category: 'Questions', directSpeech: 'Who broke the window?', context: 'Identify Role', options: ['Object', 'Subject', 'Adverb', 'Verb'], correctAnswer: 'Subject', explanation: '"Who" performs the action.', errorType: 'structure' },
    { id: '12.2', category: 'Questions', directSpeech: 'Who broke the window?', context: 'Wh-Subject conversion', options: ['who broke', 'who had broken', 'where the window broke', 'who had broken (told)'], correctAnswer: 'The teacher asked the students who had broken the window.', explanation: 'Tense backshifts; order stays (S+V).', errorType: 'tense' },
    { id: '12.3', category: 'Questions', directSpeech: 'What happened yesterday?', context: 'Yesterday shift', options: ['what happened the previous day', 'what had happened yesterday', 'what had happened the previous day', 'where had happened...'], correctAnswer: 'She asked what had happened the previous day.', explanation: 'Backshift + time word change.', errorType: 'time_place' },
    { id: '12.4', category: 'Questions', directSpeech: 'Who wrote this letter?', context: 'Identify error', options: ['"did write" is wrong', '"this" -> "that"', '"said" -> "told"', 'no error'], correctAnswer: '"did write" is wrong. Since "Who" is the subject, the word order stays the same — it should be "who had written" (with tense shifted).', explanation: 'No HV needed in statement order for subject-questions.', errorType: 'structure' }
  ],
  'mod-13': [
    { id: '13.1', category: 'Questions', directSpeech: 'Where are you going?', context: 'Identify Flip', options: ['No change', 'Yes, Sub & HV swap', 'Only Wh moves', 'Only verb moves'], correctAnswer: 'Yes, Subject and Helping Verb swap positions.', explanation: 'Question order becomes statement order.', errorType: 'structure' },
    { id: '13.2', category: 'Questions', directSpeech: 'What are you doing?', context: 'Wh-Swap', options: ['what was I doing', 'what I was doing', 'what I was doing (told)', 'that I was doing'], correctAnswer: 'She asked me what I was doing.', explanation: 'Subject "I" comes before verb "was".', errorType: 'structure' },
    { id: '13.3', category: 'Questions', directSpeech: 'Why did you leave so early?', context: 'Did shift', options: ['why did I leave', 'why I left', 'why I had left', 'why had I left'], correctAnswer: 'He asked why I had left so early.', explanation: 'Past simple -> past perfect.', errorType: 'tense' },
    { id: '13.4', category: 'Questions', directSpeech: 'Double Wh-Swap', context: 'Complex Wh', options: ['where we were... and what we were', 'where we had been... and what we had been', 'where we had been... (told)', 'where were we... and what were we'], correctAnswer: 'The policeman asked us where we had been the previous night, and what we had been doing there.', explanation: 'Both clauses flip and backshift.', errorType: 'structure' }
  ],
  'mod-14': [
    { id: '14.1', category: 'Questions', directSpeech: 'Would you like some coffee?', context: 'Polite inquiry', options: ['if I would like', 'that I would like', 'if I would like (told)', 'if I will like'], correctAnswer: 'He asked me if I would like to have some coffee.', explanation: 'Treated as a Yes/No question.', errorType: 'structure' },
    { id: '14.2', category: 'Questions', directSpeech: 'Am I doing the right thing?', context: 'Self-reflection', options: ['thought if', 'wondered if', 'asked if', 'wondered that'], correctAnswer: 'He wondered if he was doing the right thing.', explanation: '"Wondered" is better for internal questions.', errorType: 'reporting_verb' },
    { id: '14.3', category: 'Questions', directSpeech: 'Do you know where he is?', context: 'Embedded question', options: ['if I knew where he was', 'if I know where he is', 'if I knew where was he', 'if I knew where he was (told)'], correctAnswer: 'She asked if I knew where he was.', explanation: 'Both levels shift back.', errorType: 'structure' },
    { id: '14.4', category: 'Questions', directSpeech: 'Polite embedded inquiry', context: 'Advanced polite', options: ['if I could tell her where it was...', 'where it is...', 'told if I could...', 'where was the library...'], correctAnswer: 'She asked if I could tell her where the library was and how she could get there.', explanation: 'Fully backshifted and smoothed.', errorType: 'structure' }
  ]
};
