import { QuizQuestion, ErrorType } from './types';

const m1Data = [
  { q: "I love playing cricket.", o: ["Question", "Command", "Statement", "Exclamation"], a: "Statement", e: "This sentence provides information about a preference." },
  { q: "Please close the door.", o: ["Statement", "Exclamation", "Question", "Command"], a: "Command", e: "This is a request or a polite order for an action." },
  { q: "What a beautiful sunset!", o: ["Statement", "Question", "Command", "Exclamation"], a: "Exclamation", e: "Expresses strong emotion and ends with an exclamation mark." },
  { q: "Have you finished your homework?", o: ["Statement", "Question", "Command", "Exclamation"], a: "Question", e: "Asks for information and ends with a question mark." },
  { q: "Work hard and succeed.", o: ["Statement", "Question", "Command", "Exclamation"], a: "Command", e: "Provides advice or instructions for the listener." },
  { q: "The earth is round.", o: ["Statement", "Question", "Command", "Exclamation"], a: "Statement", e: "A factual declaration that gives information." },
  { q: "Hurrah! We won the match!", o: ["Statement", "Question", "Command", "Exclamation"], a: "Exclamation", e: "Uses an interjection to show joy and strong emotion." },
  { q: "Where did you go yesterday?", o: ["Statement", "Question", "Command", "Exclamation"], a: "Question", e: "A Wh-question seeking specific information." },
  { q: "Don't make noise.", o: ["Statement", "Question", "Command", "Exclamation"], a: "Command", e: "A negative imperative or an order to stop an action." },
  { q: "Tell me where you were and what you did.", o: ["Question", "Statement", "Mixed (Command + Question)", "Exclamation"], a: "Mixed (Command + Question)", e: "Combines a direct instruction with inquiry elements." },
  { q: "Run quickly and hide behind the tree.", o: ["Statement", "Mixed Command", "Question", "Exclamation"], a: "Mixed Command", e: "Two separate commands joined together in one instruction." },
  { q: "Alas! What a tragedy!", o: ["Statement", "Question", "Command", "Exclamation"], a: "Exclamation", e: "Shows deep sorrow through an exclamatory structure." },
  { q: "Which is a statement?", o: ["Close the window!", "Did you see that?", "She works at a hospital.", "How wonderful!"], a: "She works at a hospital.", e: "This option simply states a fact without ordering or asking." },
  { q: "Which is a question?", o: ["I am tired.", "Are you coming?", "Please help me.", "What a surprise!"], a: "Are you coming?", e: "This seeks a response or confirmation from the listener." },
  { q: "Which is a command?", o: ["He is sleeping.", "Is she here?", "Sit down.", "Oh no!"], a: "Sit down.", e: "A direct instruction to perform a specific action." },
  { q: "Which is an exclamation?", o: ["I will go tomorrow.", "Can you help?", "Open the door.", "Bravo! Well done!"], a: "Bravo! Well done!", e: "Expresses strong approval and excitement." },
  { q: "Be quiet and listen carefully.", o: ["Statement", "Mixed (two commands)", "Question", "Exclamation"], a: "Mixed (two commands)", e: "Multiple instructions delivered to the recipient at once." },
  { q: "Who are you, and what do you want?", o: ["Statement", "Mixed (two questions)", "Command", "Exclamation"], a: "Mixed (two questions)", e: "Two distinct inquiries merged into a single delivery." },
  { q: "Which sentence has a strong emotion?", o: ["I am happy.", "What a lovely day!", "She is reading.", "Go home."], a: "What a lovely day!", e: "The structure emphasizes feeling over mere fact-sharing." },
  { q: "How does a statement typically end?", o: ["?", "!", ".", ","], a: ".", e: "A full stop marks the end of a declarative sentence." },
  { q: "How does a question typically end?", o: ["?", "!", ".", ";"], a: "?", e: "The question mark is the universal symbol for an inquiry." },
  { q: "How does an exclamation typically end?", o: ["?", "!", ".", ":"], a: "!", e: "The exclamation mark signals the delivery of high emotion." },
  { q: "A command can end with:", o: ["Only .", "Only !", "Either . or !", "Only ?"], a: "Either . or !", e: "Depending on the force of the order, it uses a period or an exclamation mark." },
  { q: "Stop talking.", o: ["Statement", "Question", "Command", "Exclamation"], a: "Command", e: "An order given directly to the subject." },
  { q: "He stopped talking.", o: ["Statement", "Question", "Command", "Exclamation"], a: "Statement", e: "A report of an event rather than an instruction." },
  { q: "Which word often appears in exclamations?", o: ["The", "What / How", "Because", "Therefore"], a: "What / How", e: "These function as intensifiers in exclamatory sentences." },
  { q: "Good morning!", o: ["Statement", "Question", "Command", "Exclamation/Greeting"], a: "Exclamation/Greeting", e: "A social expression of well-wishing and emotion." },
  { q: "Let's go for a walk.", o: ["Statement", "Question", "Command/Suggestion", "Exclamation"], a: "Command/Suggestion", e: "An inclusive instruction involving both speaker and listener." },
  { q: "Which is NOT a mixed sentence?", o: ["Come here and tell me everything.", "I am tired.", "Who is he and where is he from?", "Be calm and think clearly."], a: "I am tired.", e: "A pure assertive sentence with no other type mixed in." },
  { q: "May God bless you!", o: ["Statement", "Question", "Command", "Exclamation/Wish"], a: "Exclamation/Wish", e: "An optative sentence expressing a prayer or blessing." },
  { q: "How old are you?", o: ["Statement", "Question", "Command", "Exclamation"], a: "Question", e: "Asks for a specific piece of information (age)." },
  { q: "I wonder what time it is.", o: ["Statement", "Question", "Command", "Exclamation"], a: "Statement", e: "Even though it refers to a question, the sentence declares a personal thought." },
  { q: "Please don't go.", o: ["Statement", "Question", "Command/Request", "Exclamation"], a: "Command/Request", e: "A polite negative imperative asking for an action to stop." },
  { q: "What happened here?", o: ["Statement", "Question", "Command", "Exclamation"], a: "Question", e: "Seeking info about past events." },
  { q: "Oh! I forgot my keys!", o: ["Statement", "Question", "Command", "Exclamation"], a: "Exclamation", e: "Signals a sudden realization with strong feeling." },
  { q: "Can you close the door?", o: ["Statement", "Question", "Command", "Exclamation"], a: "Question", e: "Phrased as an inquiry into someone's ability or willingness." },
  { q: "She can close the door.", o: ["Statement", "Question", "Command", "Exclamation"], a: "Statement", e: "A declaration of her ability." },
  { q: "A sentence that gives information is called:", o: ["Interrogative", "Imperative", "Assertive", "Exclamatory"], a: "Assertive", e: "Assertive (or declarative) sentences provide facts and data." },
  { q: "A sentence that asks for information is called:", o: ["Interrogative", "Imperative", "Assertive", "Exclamatory"], a: "Interrogative", e: "Interrogative sentences are the questions of the language." },
  { q: "A sentence that gives an order is called:", o: ["Interrogative", "Imperative", "Assertive", "Exclamatory"], a: "Imperative", e: "Imperative sentences deliver commands or requests." },
  { q: "A sentence that expresses strong emotion is called:", o: ["Interrogative", "Imperative", "Assertive", "Exclamatory"], a: "Exclamatory", e: "Exclamatory sentences focus on feelings." },
  { q: "Never give up!", o: ["Statement", "Question", "Command", "Exclamation"], a: "Command", e: "A motivational instruction or advice." },
  { q: "How dare you speak to me like that!", o: ["Statement", "Question", "Command", "Exclamation"], a: "Exclamation", e: "Expresses shock and strong indignation." },
  { q: "Listen carefully, understand the problem, and solve it step by step.", o: ["Statement", "Mixed (three commands)", "Question", "Exclamation"], a: "Mixed (three commands)", e: "A series of distinct instructions delivered together." },
  { q: "Which sentence is purely a statement with no other type mixed in?", o: ["The sky is blue.", "Is the sky blue?", "Look at the blue sky!", "What a blue sky!"], a: "The sky is blue.", e: "A basic, unmixed declaration of fact." },
  { q: "Go home now. vs I am going home now. — The difference is:", o: ["Both are statements", "First is command, second is statement", "Both are commands", "First is question, second is statement"], a: "First is command, second is statement", e: "The first orders action; the second reports status." },
  { q: "Did he leave? vs He left. — The difference is:", o: ["Both are questions", "First is question, second is statement", "Both are statements", "First is statement, second is question"], a: "First is question, second is statement", e: "The first seeks info; the second provides it." },
  { q: "Which typically has an interjection (Hurrah, Alas, Oh)?", o: ["Statement", "Question", "Command", "Exclamation"], a: "Exclamation", e: "Interjections are the vocal markers of strong emotion." },
  { q: "Bring me that book, please.", o: ["Statement", "Question", "Command/Request", "Exclamation"], a: "Command/Request", e: "An imperative sentence with a politeness marker." },
  { q: "If a sentence tells you to do something, it is most likely a:", o: ["Statement", "Question", "Command", "Exclamation"], a: "Command", e: "Commands are the directives that guide behavior." }
];

const m2Data = [
  { q: "In 'Ram said, I am happy.' — what is the Reporting Verb?", o: ["happy", "am", "said", "Ram"], a: "said", e: "The reporting verb introduces the speech act within the reporting clause." },
  { q: "In 'She told him that she was tired.' — what is the Reported Clause?", o: ["She told him", "that she was tired", "told him that", "She"], a: "that she was tired", e: "The reported clause contains the content of the message being reported." },
  { q: "The Reporting Clause contains:", o: ["The exact words spoken", "The speaker and reporting verb", "Only the listener", "Only the time"], a: "The speaker and reporting verb", e: "It identifies who is speaking and how they delivered the message." },
  { q: "The Reported Clause contains:", o: ["The speaker", "The exact or modified words spoken", "The reporting verb", "The time of speaking"], a: "The exact or modified words spoken", e: "This is the 'payload' of the sentence." },
  { q: "Which is the speaker in 'John said, I am leaving'?", o: ["I", "John", "said", "leaving"], a: "John", e: "The speaker is the subject who initiates the communication." },
  { q: "Which is the listener in 'He told me that he was busy'?", o: ["He", "me", "busy", "told"], a: "me", e: "The listener (object) is the recipient specified in the reporting clause." },
  { q: "How many main elements can change during conversion?", o: ["Three", "Four", "Five", "Six"], a: "Five", e: "We check: Quotes, Verb, Pronoun, Tense, and Time/Place (TRPT + Quotes)." },
  { q: "Which element is removed when converting to Indirect Speech?", o: ["Subject", "Verb", "Quotation marks", "Tense"], a: "Quotation marks", e: "Indirect reports focus on meaning and remove original word-for-word markers." },
  { q: "Which connector typically replaces quotation marks in statements?", o: ["if", "that", "to", "whether"], a: "that", e: "For statements, 'that' acts as the bridge between reporting and reported clauses." },
  { q: "What is the reporting verb in 'She asked, Where are you going?'?", o: ["Where", "asked", "going", "She"], a: "asked", e: "Asked is the verb identifying an interrogative speech act." },
  { q: "The TRPT mantra stands for:", o: ["Time, Reporting, Pronoun, Tense", "Tense, Reporting verb, Pronoun, Time/Place", "Tone, Report, People, Tense", "Tense, Reaction, Purpose, Time"], a: "Tense, Reporting verb, Pronoun, Time/Place", e: "A systematic checklist for reliable conversion." },
  { q: "Why do pronouns change in Indirect Speech?", o: ["Grammar rule", "The speaker is now being reported by someone else", "To make it sound formal", "No reason"], a: "The speaker is now being reported by someone else", e: "The perspective shifts from the original speaker to the person reporting." },
  { q: "Why do time words change (e.g., today → that day)?", o: ["Grammar requirement", "Time gap between speaking and reporting", "To make it longer", "They don't change"], a: "Time gap between speaking and reporting", e: "The 'Now' of the speaker is in the past for the reporter." },
  { q: "Why does tense shift back (e.g., am → was)?", o: ["The reporting verb is in the past", "To sound polite", "Random rule", "It doesn't shift"], a: "The reporting verb is in the past", e: "The backshift represents the move from present reality to reported past." },
  { q: "He said to me' changes to which in Indirect Speech?", o: ["He said me", "He told me", "He asked me", "He spoke me"], a: "He told me", e: "In statements, 'said to' + object is standardized as 'told'." },
  { q: "If there is NO listener (He said), does 'said' change?", o: ["Yes, to 'told'", "No, it stays 'said'", "Yes, to 'asked'", "Yes, to 'spoke'"], a: "No, it stays 'said'", e: "Told requires a recipient; said can stand alone." },
  { q: "Ram said something on Monday. You report it on Wednesday. Which shift is certain?", o: ["Tense shift", "Time word shift", "Pronoun shift", "All of the above"], a: "All of the above", e: "The time gap and perspective shift trigger the full TRPT process." },
  { q: "In 'She says, I am ready' — what is the time of speaking?", o: ["Past", "Present", "Future", "Unknown"], a: "Present", e: "The present tense 'says' indicates the speech act is happening now." },
  { q: "Which is NOT one of the five changing elements?", o: ["Quotation marks", "Reporting verb", "Font style", "Tense"], a: "Font style", e: "Grammar is concerned with structure, not visual presentation." },
  { q: "The gap between 'time of speaking' and 'time of reporting' causes:", o: ["No changes", "Shifts in pronouns, tense, and time/place words", "Only tense shift", "Only pronoun shift"], a: "Shifts in pronouns, tense, and time/place words", e: "This gap defines the necessity of the Indirect form." },
  { q: "What does 'backshift' mean?", o: ["Moving tenses forward", "Moving tenses one step back in time", "Removing tenses", "Changing pronouns"], a: "Moving tenses one step back in time", e: "Backshift aligns the reported message with the reporter's timeline." },
  { q: "In Indirect Speech, the exact words are:", o: ["Quoted", "Paraphrased/Modified", "Removed", "Unchanged"], a: "Paraphrased/Modified", e: "We report the meaning, adjusting pronouns and tenses to fit." },
  { q: "The reporting verb 'said to' + object becomes:", o: ["said", "told", "asked", "spoke"], a: "told", e: "This is the primary transformation for assertive reporting with an object." },
  { q: "If the reporting verb is present tense (says), what happens to the reported speech tense?", o: ["Shifts back", "Stays the same", "Shifts forward", "Doubles"], a: "Stays the same", e: "A present reporting verb 'locks' the reported tense in its original state." },
  { q: "What is the subject in 'The teacher told the students that they should study'?", o: ["The teacher", "the students", "told", "study"], a: "The teacher", e: "The teacher is the one performing the reporting act." },
  { q: "What is the object in 'He told me that he was ill'?", o: ["He", "me", "told", "ill"], a: "me", e: "Me is the recipient specified in the reporting clause." },
  { q: "Which part tells WHO said it?", o: ["Reported clause", "Reporting clause", "Quotation marks", "Connector"], a: "Reporting clause", e: "It establishes the identity of the original speaker." },
  { q: "Which part tells WHAT was said?", o: ["Reported clause", "Reporting clause", "Speaker", "Listener"], a: "Reported clause", e: "This is the actual informational payload." },
  { q: "'I' in Direct Speech (speaker's words) becomes:", o: ["I always", "Follows the subject of reporting verb", "Follows the object", "Stays I"], a: "Follows the subject of reporting verb", e: "The reporter refers back to the speaker in the 3rd person." },
  { q: "'You' in Direct Speech (listener's words) becomes:", o: ["You always", "Follows the subject", "Follows the object", "Stays you"], a: "Follows the object", e: "The reported pronoun reflects who was originally listening." },
  { q: "Third person pronouns (he, she, they) in Direct Speech:", o: ["Always change", "Never change", "Sometimes change", "Become I/we"], a: "Never change", e: "Third parties remain third parties; no perspective shift occurs." },
  { q: "If Ram says 'I am happy' and you report it, 'I' becomes:", o: ["I", "he", "you", "we"], a: "he", e: "Ram is a third person to the reporter." },
  { q: "If Ram says 'You are smart' to you, and you report it, 'You' becomes:", o: ["you", "I", "he", "we"], a: "I", e: "Since the reporter was the listener, the perspective shifts to 'I'." },
  { q: "The five elements are: Quotation marks, Reporting verb, Tense, Pronouns, and:", o: ["Punctuation", "Time & Place words", "Speaker", "Listener"], a: "Time & Place words", e: "This is the fourth pillar of the TRPT checklist." },
  { q: "Which changes ONLY when reporting verb is past?", o: ["Pronouns", "Quotation marks", "Tense", "Reporting verb"], a: "Tense", e: "Pronouns and time words can change in present reporting, but tense backshift is exclusive to past verbs." },
  { q: "The speaker in 'Maya said, I love books' is:", o: ["I", "Maya", "books", "love"], a: "Maya", e: "Maya is the initiator of the original statement." },
  { q: "The listener in 'He said to her, You are kind' is:", o: ["He", "her", "kind", "You"], a: "her", e: "Her is the recipient of the direct address." },
  { q: "In 'I said to the boys, You must come', the object is:", o: ["I", "the boys", "You", "come"], a: "the boys", e: "The group receiving the instruction is the object." },
  { q: "Reporting structures exist to:", o: ["Make sentences longer", "Report what someone said without using exact quotes", "Confuse students", "Add punctuation"], a: "Report what someone said without using exact quotes", e: "They allow for narrative flow and formal documentation." },
  { q: "Direct Speech is like:", o: ["Paraphrasing", "Quoting", "Summarizing", "Translating"], a: "Quoting", e: "It acts like a tape recorder capturing exact sounds." },
  { q: "Indirect Speech is like:", o: ["Quoting", "Paraphrasing with context", "Copying", "Ignoring"], a: "Paraphrasing with context", e: "It conveys the meaning while aligning with the reporter's scene." },
  { q: "When does NO tense change happen?", o: ["Always", "When reporting verb is past", "When reporting verb is present/future", "Never"], a: "When reporting verb is present/future", e: "Present and future introductions block the backshift process." },
  { q: "He will say, 'I am tired' — Will the tense of 'am' change?", o: ["Yes", "No", "Sometimes", "Only if past"], a: "No", e: "The future verb 'will say' prevents the internal tense from shifting." },
  { q: "Context matters. If I report something said 5 seconds ago, should time words change?", o: ["Always change", "May not need to change (context-dependent)", "Never change", "Only pronouns change"], a: "May not need to change (context-dependent)", e: "If the 'Now' is still relevant, shifts like 'today' might be skipped." },
  { q: "The phrase 'Time of Speaking' means:", o: ["When we report it", "When it was originally said", "Current time", "Future time"], a: "When it was originally said", e: "This is the moment of the original direct speech." },
  { q: "The phrase 'Time of Reporting' means:", o: ["When it was originally said", "When we are NOW reporting it", "Past time", "When we will report"], a: "When we are NOW reporting it", e: "This is the moment of the indirect speech act." },
  { q: "If speaker and reporter are the same person (I said, I am happy), does 'I' change?", o: ["Yes, to he", "No, stays I", "Yes, to we", "Yes, to you"], a: "No, stays I", e: "The identity remains the same, so no perspective shift is needed." },
  { q: "Understanding WHY things change helps you:", o: ["Memorize blindly", "Apply rules logically", "Avoid grammar", "Ignore rules"], a: "Apply rules logically", e: "Logic allows you to handle complex sentences that simple rules miss." },
  { q: "Which is more important to understand first?", o: ["Individual rules", "The framework and WHY changes happen", "Memorizing examples", "Skipping theory"], a: "The framework and WHY changes happen", e: "The 'Post Office' framework gives context to every individual rule." },
  { q: "The TRPT order helps you:", o: ["Randomly change things", "Systematically check each element", "Skip steps", "Confuse yourself"], a: "Systematically check each element", e: "It ensures a high-accuracy delivery every single time." }
];

const finalize = (data: { q: string, o: string[], a: string, e: string }[], mod: number, cat: string): QuizQuestion[] => 
  data.map((item, idx) => ({
    id: `${mod}.${idx + 1}`,
    category: cat,
    directSpeech: item.q,
    context: `Conceptual Mastery Level ${mod}`,
    options: item.o,
    correctAnswer: item.a,
    explanation: item.e,
    errorType: (mod === 1 ? 'sentence_type' : 'structure') as ErrorType
  }));

export const quizFoundations: Record<string, QuizQuestion[]> = {
  'mod-1': finalize(m1Data, 1, 'Foundations'),
  'mod-2': finalize(m2Data, 2, 'Foundations')
};