
import { QuizQuestion } from './types';

export const quizMastery: Record<string, QuizQuestion[]> = {
  'mod-27': [
    { id: '27.1', category: 'Mastery', directSpeech: 'He told me that he was ill.', context: 'Reverse conversion', options: ['I was ill', 'I am ill', 'I am ill (told)', 'He is ill'], correctAnswer: 'He said to me, "I am ill."', explanation: 'Back to direct: was -> am; told -> said to.', errorType: 'general' },
    { id: '27.2', category: 'Mastery', directSpeech: 'She said that she had passed the exam.', context: 'Reverse perfect', options: ['I have passed', 'I had passed', 'She has passed', 'I passed'], correctAnswer: 'She said, "I have passed the examination."', explanation: 'Restore quotes and present perfect.', errorType: 'general' },
    { id: '27.3', category: 'Mastery', directSpeech: 'I would visit him the next day.', context: 'Reverse time', options: ['the next day', 'tomorrow', 'tomorrow (no quotes)', 'would visit tomorrow'], correctAnswer: 'I wrote to him, "I will visit you tomorrow."', explanation: 'the next day -> tomorrow.', errorType: 'time_place' },
    { id: '27.4', category: 'Mastery', directSpeech: 'Complex reverse statement', context: 'Advanced reverse', options: ['met... ago... felt... now', 'met... ago... feel... now', 'had met... ago...', 'meet... ago...'], correctAnswer: 'He said, "I met this man two days ago, and I feel very uneasy now."', explanation: 'Reverse all 5 pillars.', errorType: 'time_place' }
  ],
  'mod-28': [
    { id: '28.1', category: 'Mastery', directSpeech: 'He asked me what I wanted.', context: 'Reverse question', options: ['What do you want?', 'What did you want?', 'What do you want? (asked)', 'What does you want?'], correctAnswer: 'He said to me, "What do you want?"', explanation: 'Restore question order.', errorType: 'structure' },
    { id: '28.2', category: 'Mastery', directSpeech: 'The captain commanded his soldiers to attack.', context: 'Reverse imperative', options: ['Attack the enemy.', 'Please attack the enemy.', 'Attack the enemy. (asked)', 'Attack the enemy. (no quotes)'], correctAnswer: 'The captain said to his soldiers, "Attack the enemy."', explanation: 'Restore direct command.', errorType: 'reporting_verb' },
    { id: '28.3', category: 'Mastery', directSpeech: 'He asked when the next letter would come.', context: 'Reverse Wh-question', options: ['When will the next letter come?', 'When would...', 'When will... (asked)', 'When does...'], correctAnswer: 'He said to his father, "When will the next letter come?"', explanation: 'would -> will; restore order.', errorType: 'tense' },
    { id: '28.4', category: 'Mastery', directSpeech: 'Complex reverse inquiry', context: 'Advanced reverse mixed', options: ['Do you remember... yesterday? Please follow...', 'Did you remember...', 'Do you remember... Follow...', 'Do you remember... tell...'], correctAnswer: 'She said to me, "Do you remember what I told you yesterday? Please follow my advice."', explanation: 'Full restoration of quotes and tone.', errorType: 'general' }
  ],
  'mod-29': [
    { id: '29.1', category: 'Mastery', directSpeech: 'Diagnosis: Identify error', context: 'Common mistakes', options: ['He told me he was busy', 'He said to me that he was busy', 'She said she was happy', 'They said they were ready'], correctAnswer: 'He said to me that he was busy.', explanation: 'Avoid using "said to" in indirect speech.', errorType: 'reporting_verb' },
    { id: '29.2', category: 'Mastery', directSpeech: 'She asked him that he was coming.', context: 'Identify error', options: ['asked -> told', 'that -> if/whether', 'him -> her', 'was -> is'], correctAnswer: '"that" should be "if/whether" — it is a Yes/No question.', explanation: 'Questions use if/whether, not that.', errorType: 'structure' },
    { id: '29.3', category: 'Mastery', directSpeech: 'I will come here tomorrow.', context: 'Find ALL errors', options: ['only will -> would', 'will -> would / here tomorrow -> there the next day', 'will -> would / here -> there / tomorrow -> next day', 'no errors'], correctAnswer: 'Three errors: "will" should be "would", "here" should be "there", and "tomorrow" should be "the next day".', explanation: 'Multiple shifts required.', errorType: 'general' },
    { id: '29.4', category: 'Mastery', directSpeech: 'Diagnosis: Universal truth', context: 'Advanced truth check', options: ['Fully correct', 'Both "was" and "boiled" are wrong', 'Only "was" is wrong', 'Only "boiled" is wrong'], correctAnswer: 'Both "was round" and "boiled" are wrong. These are universal truths — tense should NOT change. Correct: The teacher said that the earth is round and water boils at 100°C.', explanation: 'TRPT exception for facts.', errorType: 'no_change' }
  ],
  'mod-30': [
    { id: '30.1', category: 'Mastery', directSpeech: 'I will meet you here tomorrow.', context: 'Full mixed check', options: ['told me... would... there the next day', 'will meet you here tomorrow', 'said to me... would...', 'would meet you here tomorrow'], correctAnswer: 'He told me that he would meet me there the next day.', explanation: 'Full TRPT compliance.', errorType: 'general' },
    { id: '30.2', category: 'Mastery', directSpeech: 'What a wonderful experience this has been!', context: 'Mixed exclamation', options: ['was a wonderful', 'had been a very wonderful', 'with joy that it had been', 'said that it had been very'], correctAnswer: 'She exclaimed that it had been a very wonderful experience.', explanation: 'What a -> very; has been -> had been.', errorType: 'tense' },
    { id: '30.3', category: 'Mastery', directSpeech: 'Have you completed assignments? If not, finish today.', context: 'Mixed question/command', options: ['asked... if they had... and told them to finish that day', 'have completed... finish today', 'told... if they had...', 'asked whether... advised them...'], correctAnswer: 'The teacher asked the students if they had completed their assignments, and told them to finish them that day if not.', explanation: 'Combined question and imperative rules.', errorType: 'general' },
    { id: '30.4', category: 'Mastery', directSpeech: 'Complex mixed multi-sentence', context: 'Final delivery test', options: ['asked... remembered... had told... warned... believed was', 'remember... told... warns...', 'told me if... remembered...', 'believes he is...'], correctAnswer: 'She asked me if I remembered what she had told me the previous day. She said that she had warned me not to trust him, and that she still believed he was not to be trusted.', explanation: 'Ultimate TRPT and sentence integration.', errorType: 'general' }
  ]
};
